---
title: "Voom+Limma for raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(edgeR)
library(limma)
```

## prepare data

```{r}
# code from Michelle
countdata_filt<-read.table("../data/after_filter/data.chrfl.txt.mappPE.mean0.8fl", header=F)
header<-read.table("../data/after_filter/header.txt",header=F)
metapeaks.hg19.filt.raw<-read.table("../data/after_filter/comm.hg19.bed.ortho.hg19.mappinput.chrfl.mappPE.mean0.8.bed.mappfl",header=F)
metapeaks.panTro3.filt.raw<-read.table("../data/after_filter/comm.hg19.bed.ortho.panTro3.mappinput.chrfl.mappPE.mean0.8.bed.mappfl",header=F)

rownames(countdata_filt) <- metapeaks.hg19.filt.raw[,4]
colnames(countdata_filt)<-as.matrix((header[1,]))
colnames(metapeaks.hg19.filt.raw) <- c("Chr", "Start", "End", "Peak")
colnames(metapeaks.panTro3.filt.raw) <- c("Chr", "Start", "End", "Peak")
countdata_filt_noH20961 <- countdata_filt[,c(1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
                                             21,22,24,25,26,27,28,29,30,31,32,33,34)]
H3K9countdata_noH20961<-countdata_filt_noH20961[,c(2,5,6,7,8,10,13,15,17,18,19,20,23,26,27,32)]
chipcounts100 =  H3K9countdata_noH20961[apply( H3K9countdata_noH20961>0,1,sum) > 10, ]
condition_chip = c("H", "H", "H", "C", "C", "C", "C", "H", "H", "H", "C", "H", "H", "C", "C", "H")
input <- list(counts= chipcounts100, condition = condition_chip)
```

## calculate normalization factors
```{r  echo=TRUE, cathe=T}
dgecounts = calcNormFactors(DGEList(counts=input$counts,group=input$condition))
```

## voom + limma
```{r  echo=TRUE, cathe=T}
design = model.matrix(~input$condition)
v = voom(dgecounts,design,plot=TRUE)
``` 
## limma
```{r  echo=TRUE, cathe=T}
lim = lmFit(v)
lim = eBayes(lim)
saveRDS(lim, file="../output/VL.fit.RDS")
```

### Distribution of z score
```{r echo=T}
hist(lim$t, breaks=400, xlim=c(-20,20),col="lightgrey", border="gray", main ="z-score distribution")
abline(v=0,col="red",lwd=2)
```

### singular values of residuals

```{r echo=T, cathe=T}
resid <- v$E - lim$coefficients %*% t(lim$design)
d <- svd(resid)
plot(d$d, ylab="singlar value")
```

### PCA
```{r echo=T, cathe=T}
pcafit <- prcomp(t(resid))
summary(pcafit) # print variance accounted for 
plot(pcafit,type="lines") # scree plot 
plot(pcafit$x,col=as.factor(input$condition),pch=16)
grid()
legend("topright",c("Human", "Chimp"), col=c("red","black"),pch=16)
```

## Estimate number of hidden confounders with `sva::num.sv`

```{r cathe=T}
svout <- sva::num.sv(dat = v$E, mod = design)
svout
```
